#spring.application.name=config-server

server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Pedro410Ar/MicroserviciosFlight.git
          search-paths: config-data
  application:
    name: config-server
