#spring.application.name=eureka-server2


spring:
    application:
        name: eureka-server2
server:
    port: 8761
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
